"""
Course Number: ENGR 13300
Semester: Fall 2026

Description:
    Ask the user for a genotype and print the corresponding physical feature based on the data from the CSV file

Assignment Information:
    Assignment:     15.3.1 py3 ind 1 
    Team ID:        LC5 - 16
    Author:         Stephen Lim, lim573@purdue.edu
    Date:           9/29/2026

Contributors:
    Name, login@purdue [repeat for each]

    My contributor(s) helped me:
    [ ] understand the assignment expectations without
        telling me how they will approach it.
    [ ] understand different ways to think about a solution
        without helping me plan my solution.
    [ ] think through the meaning of a specific error or
        bug present in my code without looking at my code.
    Note that if you helped somebody else with their code, you
    have to list that person as a contributor here as well.

Academic Integrity Statement:
    I have not used source code obtained from any unauthorized
    source, either modified or unmodified; nor have I provided
    another student access to my code.  The project I am
    submitting is my own original work.
"""

import pandas as pd

def main():
    #load csv
    data = pd.read_csv('list_of_features.csv')
    #fill in the rows without labels, anything below the original label without a label needs a label
    data['Feature'] = data['Feature'].ffill()

    #create blank dictionary and initialize again as "y"
    data_dict = {}
    again = "y"

    #fill in dictionary
    for i in range(len(data)):
        fea_i = data.loc[i, 'Feature']
        gen_i = data.loc[i, 'Genotype']
        #loc means location, i is the index (it is accessing a row), the second parameter is for column name.
        
        if fea_i not in data_dict:
            data_dict[fea_i] = []
        #if feature list is not in data_dictionary yet add it
        data_dict[fea_i].append(gen_i)
        #example of how it looks
        #{Hair_type:["AA", "Aa", "aa"]}
    features = list(data_dict.keys())

    if again == "y":
        print("AVAILABLE FEATURES:")
        for i in features:
            print(i)

    feature_choice = input('Please select a feature: ')
    genotypes = []

    #loop through dictionary list and find genotypes
    if feature_choice in data_dict:
        print(f"POSSIBLE GENOTYPES:")
        for i in data_dict[feature_choice]:
            print(i)
        genotypes = data_dict[feature_choice]
        #search for the genotype index, then print out the phenotype with the corresponding index
        genotype = input("Please input the genotype: ")
        if genotype in genotypes:
            # Loop through the rows to find the exact match for BOTH feature and genotype
            for i in range(len(data)):
                if data.loc[i, 'Feature'] == feature_choice and data.loc[i, 'Genotype'] == genotype: # generated by Gemini, specifically the first part of the if statement.
                    phenotype = data.loc[i, 'Phenotype']
                    print("This corresponds to the physical attribute: " + phenotype)
                    break
        else:
            print("Invalid genotype.")
    else:
        print("Invalid feature.")


    again = input("Would you like to run again (y or n)? ")

    if again == "y":
        main()
    else:
        return

if __name__ == "__main__":
    main()